FROM webhippie/alpine:latest@sha256:b469df22825172f94b3d8142dd687ac3fc8a6e7d79ac398c02baa9e86350587d

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="RabbitMQ" \
  org.label-schema.vcs-url="https://github.com/dockhippie/rabbitmq.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 5671 5672 15671 15672 25672

VOLUME ["/var/lib/rabbitmq"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/rabbitmq && \
  groupadd -g 1000 rabbitmq && \
  useradd -u 1000 -d /var/lib/rabbitmq -g rabbitmq -s /bin/bash -m rabbitmq && \
  apk add rabbitmq-server && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-amd64 /
