FROM webhippie/alpine:latest-arm64v8@sha256:248d3c19cd10e084aee1ad346ba0b1068d5cdeed5ef3dce5dce3e0ec26a07eb8

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="RabbitMQ" \
  org.label-schema.vcs-url="https://github.com/dockhippie/rabbitmq.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 5671 5672 15671 15672 25672

VOLUME ["/var/lib/rabbitmq"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/rabbitmq && \
  groupadd -g 1000 rabbitmq && \
  useradd -u 1000 -d /var/lib/rabbitmq -g rabbitmq -s /bin/bash -m rabbitmq && \
  apk add rabbitmq-server && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-arm64v8 /
