FROM webhippie/alpine:latest-arm32v6@sha256:f52146000ae31a8e6df968e3ab3680f5d799b1e5cb2100fa90ec71584068b0a7

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="RabbitMQ" \
  org.label-schema.vcs-url="https://github.com/dockhippie/rabbitmq.git" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

EXPOSE 5671 5672 15671 15672 25672

VOLUME ["/var/lib/rabbitmq"]
WORKDIR /root
ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/bin/s6-svscan", "/etc/s6"]

RUN apk update && \
  apk upgrade && \
  mkdir -p /var/lib/rabbitmq && \
  groupadd -g 1000 rabbitmq && \
  useradd -u 1000 -d /var/lib/rabbitmq -g rabbitmq -s /bin/bash -m rabbitmq && \
  apk add rabbitmq-server && \
  rm -rf /var/cache/apk/*

COPY ./overlay ./overlay-arm32v6 /
